-- Crear base de datos si no existe
CREATE DATABASE IF NOT EXISTS MultiDBAcademy;
USE MultiDBAcademy;

-- Tabla Roles
CREATE TABLE IF NOT EXISTS Roles (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL
);

-- Tabla Users
CREATE TABLE IF NOT EXISTS Users (
    Id CHAR(36) PRIMARY KEY,
    UserName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PassHash VARCHAR(500) NOT NULL,
    RefreshToken VARCHAR(500),
    RefreshTokenExpire DATETIME,
    RoleId INT NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

-- Tabla InstancesDB
CREATE TABLE IF NOT EXISTS InstancesDB (
    Id CHAR(36) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Type VARCHAR(100) NOT NULL,
    State VARCHAR(50) NOT NULL,
    Ports VARCHAR(50) NOT NULL,
    UserId CHAR(36) NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

-- Tabla Logs
CREATE TABLE IF NOT EXISTS Logs (
    Id CHAR(36) PRIMARY KEY,
    InstanceId CHAR(36) NOT NULL,
    Action VARCHAR(255) NOT NULL,
    Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (InstanceId) REFERENCES InstancesDB(Id)
);

-- Insertar roles por defecto
INSERT INTO Roles (Id, Name) VALUES (1, 'Admin'), (2, 'Student')
ON DUPLICATE KEY UPDATE Name=Name;
